### PR TITLE
fix(preseed): larger root partition for vxscan

### PR DESCRIPTION
**Pull request by benadida**

### CODE REVIEW

**Review by eventualbuddha — APPROVED** [review]

**Comment by umbernhard** [comment]
Do we just want to have a separate preseed file for VxScan?

**Comment by benadida** [comment]
> Do we just want to have a separate preseed file for VxScan?

I would recommend same one for everything. Wasting 1-2GB in exchange for consistency / simplicity feels like the right tradeoff.

**Comment by benadida** [comment]
confirmed that this works, changing to non-draft.

**Review by umbernhard — APPROVED** [review]

**Comment by umbernhard** [comment]
hmm, I'm still getting an out of room error even with the 8G partition.

**Comment by umbernhard** [comment]
this time it's `/home`

**Comment by umbernhard** [comment]
oops, github shortcuts strike again. Sorry for the label!

**Comment by umbernhard** [comment]
yep, works for me.

**Comment by benadida** [comment]
> ah, I think it's because I had all the plustek stuff on my home partition. Lemme try removing that...

Yes, I hit that too... might be worth thinking about building out of `/var` and then clearing that out, rather than using `/home`, and then we can shrink `/home` even more. Next time!

**Pull request merged**
