### PR TITLE
feat(admin-menu): Clean up admin menu

### PR DESCRIPTION
**Pull request by jonahkagan**
Task: https://github.com/votingworks/vxsuite/issues/1448

- Make capitalization/punctuation consistent
- Move most commands into scripts
- Change tabs to spaces
- Standardize internal menu item naming format
- Reorder menu items
- Change the time to a more human-friendly format
- Change the QR code output to be more easily picked up by a camera

### CODE REVIEW

**Review by benadida — APPROVED** [review]
Assuming you've tested on a locked down machine in tty2?

**Comment by benadida** [comment]
> @benadida I don't have a locked down machine to test with - but I can try locking down my Lenovo laptop and trying it. Once I lock it down, I have to reinstall Ubuntu to undo it right?

you can snapshot your VM, lock down in the VM, test there, and then rewind. No need to test on hardware itself.

**Comment by jonahkagan** [comment]
Successfully tested these changes on a locked down VM

**Pull request merged**
